config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/' => 'main#index'

  post '/results' => 'main#results'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get '/users/newAddress' => 'users#newAddress'
  get '/users/deleteAddress' => 'users#deleteAddress'
  
  get '/location' => 'main#location'
  post '/users/new' => 'users#create'

  resource :users

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/controllers/main_controller.rb
require 'open-uri'

class MainController < ApplicationController
	@@BASE_CHARGE = 1.35
	@@BASE_CHARGE_P = 2.02
	@@MINIMUM = 4.00
	@@MINIMUM_P = 6.00
	@@COSTPERMILE = 1.35
	@@COSTPERMILE_P = 2.02
	@@COSTPERMINUTE = 0.24
	@@COSTPERMINUTE_P = 0.36
	@@TRUSTFEE = 1.95
	@@count = 0


	def index
		if @current_user
			@addresses = @current_user.address
		end
		@map_data = State.select("id,state,uberfare,lyftfare,count,milestotal").order("id ASC")
		gon.mapData = @map_data
	end

	def update
		@map_data = State.select("id,state,uberfare,lyftfare,count,milestotal").order("id ASC")
		gon.mapData = @map_data
	end

	def location
		latlng = params["latlng"]
		unless latlng.present?
			flash[:danger] = "Unable to locate address, please try again"
			render :json => { :success => false }
		else
			url =  'https://maps.googleapis.com/maps/api/geocode/json?latlng='+latlng+'&result_type=street_address&key='+ ENV["GSERVER"]
			response = open(url).read
		    render json: response
		end
	end

	def results
		@codes = get_code
		@to = params_pass["to"]
		@from = params_pass["from"]
		coords = Geocoder.coordinates(@from) 
		location = Geocoder.coordinates(@to);

		unless coords.present?
			flash[:danger] = "Unable to locate #{@to}, please try again"
			redirect_to root_path and return
		end

		unless location.present?
			flash[:danger] = "Unable to locate #{@from}, please try again"
			redirect_to root_path and return
		end


		dlat = coords[0]
		dlon = coords[1]
		slat = location[0]
		slon = location[1]
		start = location[0].to_s + "," + location[1].to_s
		stop = dlat.to_s + "," + dlon.to_s

		urls =  'https://maps.googleapis.com/maps/api/geocode/json?latlng='+start+'&result_type=street_address&key='+ ENV["GSERVER"]
		urld =  'https://maps.googleapis.com/maps/api/geocode/json?latlng='+stop+'&result_type=street_address&key='+ ENV["GSERVER"]
		startresponse = open(urls).read
		stopresponse = open(urld).read

		add1 = JSON.parse(startresponse)
		add2 = JSON.parse(stopresponse)
		
		dropoff = add1["results"][0]["formatted_address"]
		pickup = add2["results"][0]["formatted_address"]

		@uberString="uber://?client_id="+ENV["CLIENT"]+"&action=setPickup&pickup[latitude]="+dlat.to_s+"&pickup[longitude]="+dlon.to_s+"&pickup[nickname]=You%20Are%20Here&pickup[formatted_address]="+pickup.to_s+"&dropoff[latitude]="+slat.to_s+"&dropoff[longitude]="+slon.to_s+"&dropoff[nickname]=Your%20Destination&dropoff[formatted_address]="+dropoff.to_s+"&product_id=a1111c8c-c720-46c3-8534-2fcdd730040d"

		@state = params_pass["loc"]

		client = Uber::Client.new do |config|
  		config.server_token  = ENV["TOKEN"]
		end
		
		if Geocoder::Calculations.distance_between([slat,slon], [dlat,dlon]) > 100
			flash[:danger] = "Distance cannot exceed 100 miles."
			redirect_to root_path and return
		end

		data = client.price_estimations(start_latitude: slat, start_longitude: slon,
                          end_latitude: dlat, end_longitude: dlon)
		@location = {"slat"=>slat,"slon"=>slon,"dlat"=>dlat,"dlon"=>dlon}
		@ride_data = [uber_lyft_data(data), add1, add2, @current_user, @state]
		uber_estimate = @ride_data[0][0].estimate.dup
		lyft_estimate = @ride_data[0][3].estimate.dup
		uber_estimate.slice!(0)
		lyft_estimate.slice!(0)
		uber_estimate = uber_estimate.split("-")
		lyft_estimate = lyft_estimate.split("-")
		uber_estimate = (uber_estimate[0].to_i+uber_estimate[1].to_i)/2.0
		lyft_estimate = (lyft_estimate[0].to_i+lyft_estimate[1].to_i)/2.0
		distance = @ride_data[0][3].distance
		this_state = State.find_by state: @state
		puts this_state.uberfare
		this_state.update_columns(uberfare: this_state.uberfare+uber_estimate)
		this_state.update_columns(lyftfare: this_state.lyftfare+lyft_estimate)
		this_state.update_columns(count: this_state.count+1)
		this_state.update_columns(milestotal: this_state.milestotal+distance)
	end

	private

	def params_pass 
		params.permit(:from, :to, :loc, :slat, :slon)
	end

	def get_code
		@codes = User.select("id,ubercode,lyftcode").order("id ASC")
		@@count = (rand(@codes.length))
		@index = @codes
		@codes = @codes[@@count % @index.length]
	 	while(@codes["ubercode"].empty? || @codes["lyftcode"].empty?)
 		@@count += rand(@index.length)
 		@codes = @index[((@@count) % @index.length)]
 		end
 		@codes
	end

	class Lyft 
		def initialize duration,estimate,distance,display_name,surge
			@duration = duration
			@estimate = estimate
			@distance = distance
			@display_name = display_name
			@surge_multiplier = surge
		end

		def duration 
			@duration
		end

		def estimate 
			@estimate
		end

		def distance 
			@distance
		end

		def display_name 
			@display_name
		end

		def surge_multiplier
			@surge
		end
	end

	def uber_lyft_data uber_data
		lyft_est =  lyft_charge(uber_data[0]["distance"],uber_data[0]["duration"]).floor
		lyft_p_est = lyft_charge_p(uber_data[0]["distance"],uber_data[0]["duration"]).floor

		lyft = Lyft.new(uber_data[0][:duration],"$"+lyft_est.to_s+ "-" +(lyft_est+2).to_s,uber_data[0][:distance],"Lyft","To be Determined")
		lyft_p = Lyft.new(uber_data[0][:duration],"$"+lyft_p_est.to_s+ "-" +(lyft_p_est+3).to_s,uber_data[0][:distance],"Lyft Plus","To be Determined")
		
		uber = []

		uber << uber_data[0] 
		uber << uber_data[4]
		uber << uber_data[5]
		uber << lyft
		uber << lyft_p
		uber
	end

	def lyft_charge miles,minutes
		charge = @@BASE_CHARGE + (@@COSTPERMINUTE*(minutes/60)) + (@@COSTPERMILE*miles)+ @@TRUSTFEE
		puts charge
		if charge < @@MINIMUM 
		 @@MINIMUM
	    else
		 charge.round(2)
		end
	end

	def lyft_charge_p miles,minutes
		charge = @@BASE_CHARGE_P + (@@COSTPERMINUTE_P*(minutes)/60) + (@@COSTPERMILE_P*miles)+ @@TRUSTFEE;
		if charge < @@MINIMUM_P 
		 @@MINIMUM_P
	    else
		 charge.round(2)
		end
	end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<div id="navigation">
	<%= render 'partials/nav' %>
	<%= render "partials/profile" %>
</div>

<div id="fullpage-one">
	<div class="section section-1">
		<%= render "partials/flash" %>
		<p class="animated bounceInLeft"><span class="first">Fare</span>
		<span class="second">Start</span></p>
		<a href="#search" class="bottom-a"><i class="fa fa-sort-desc fa-4x animated pulse infinite bottom-i"></i></a>
	</div>

	<div class="section section-2">
		<p class="title">Search</p>
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<p class="description">Get fare quotes from Uber and Lyft, so you get the cheapest price every time.</p>
		</div>
		<div class="row">
			<div class="col-xs-10 col-sm-6 col-xs-offset-1 col-sm-offset-3">
				<%= form_tag results_path :method => :get do %>
					<%= text_field_tag :from, "", class: "form-control input-lg", placeholder: "Where are you getting picked up?" %><br>
					<% if @current_user %>
						<% if @addresses %>
							<div class="col-xs-12 col-sm-6 col-sm-offset-3">
								<select id="savedFrom" class="form-control">
									<option value="">Or Use a Saved Addresses Here</option>
									<% @addresses.each do |address| %>
										<option value="<%= address.address %>"><%= address.address %></option>
									<% end %>
								</select>
							</div>
						<% end %>
						<br>
					<% end %>
					<%= text_field_tag :to, "", class: "form-control input-lg", placeholder: "Where are you getting dropped off?" %><br>
					<% if @current_user %>
						<% if @addresses %>
							<div class="col-xs-12 col-sm-6 col-sm-offset-3">
								<select id="savedTo" class="form-control">
									<option value="">Here Too</option>
									<% @addresses.each do |address| %>
										<option value="<%= address.address %>"><%= address.address %></option>
									<% end %>
								</select>
							</div>
						<% end %>
					<% end %>

					<%= hidden_field_tag :loc %>
					<%= hidden_field_tag :slat %>
					<%= hidden_field_tag :slon %>
					<br>
					<br>
					<%= submit_tag "Find Fare", id: "sub", class: "btn btn-lg btn-default" %>
				<%end%>
			</div>
		</div>

		<a href="#data" class="bottom-a"><i class="fa fa-sort-desc fa-4x animated pulse infinite bottom-i"></i></a>
	</div>

	<div class="section section-3">
		<p id="title">There is a cool map here on the desktop version.</p>
		<p class="map-sort">
			Sort by:
			<button id="countMap" class="btn btn-lg btn-default">Count</button>
			<button id="uberMap" class="btn btn-lg btn-default">Uber</button>
			<button id="lyftMap" class="btn btn-lg btn-default">Lyft</button>
		</p>
		<div id="tooltip-container"></div>
		<div id="canvas-svg"></div>

		<a href="#about" class="bottom-a"><i class="fa fa-sort-desc fa-4x animated pulse infinite bottom-i"></i></a>
	</div>

	<div class="section section-4">
		<p class="title">About</p>
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<p class="description">Fare <span class="last">Start</span> is a full stack web application built using Ruby on Rails for General Assembly Seattle.</p>
		</div>
		<div class="row">
			<div class="col-xs-4">
				<%= image_tag("todd.jpg", class: "img-rounded img-responsive center-block") %>
				<div class="caption">
					<p class="name">Todd <br class="line-break-xs">Best</p>
					<a href="https://www.linkedin.com/in/toddbest2004" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a><a href="https://github.com/toddbest2004" target="_blank"><i class="fa fa-github-alt fa-2x"></i></a>
				</div>
			</div>
			<div class="col-xs-4">
				<%= image_tag("andrew.jpg", class: "img-rounded img-responsive center-block") %>
				<p class="name">Andrew Mestas</p>
				<a href="https://www.linkedin.com/in/andrewmestas" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a><a href="https://github.com/andrew-mestas" target="_blank"><i class="fa fa-github-alt fa-2x"></i></a>
			</div>
			<div class="col-xs-4">
				<%= image_tag("thomas.jpg", class: "img-rounded img-responsive center-block") %>
				<div class="caption">
					<p class="name">Thomas Vaeth</p>
					<a href="https://www.linkedin.com/in/thomasvaeth" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a><a href="https://github.com/thomasvaeth" target="_blank"><i class="fa fa-github-alt fa-2x"></i></a>
				</div>
			</div>
		</div>
	</div>
	
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var options = {
		  types: ['address']
		};

		var from = document.getElementById('from');
		autocomplete = new google.maps.places.Autocomplete(from, options);

		var to = document.getElementById('to')
		autocomplete2 = new google.maps.places.Autocomplete(to, options);
	});
</script>
<script type="text/javascript" src="/fullpage-home.js"></script>
<script src="/mapscript.js"></script>
<script src="/index.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_OcPqd4-0Dsx7LK_3wHvVzvKcJRWSwjQ&libraries=places"></script>

app/views/main/results.html.erb
<div id="navigation">
	<%= render "partials/nav" %>
	<%= render "partials/profile" %>
</div>

<div id="fullpage-two">
	<div class="section section-5">
		<% @ride_data[4] %>
		<%= render "partials/flash" %>
		<p class="title">Quotes</p>
		<div id="fromAddress">
			<% if @current_user %>
	  		<button id="saveFrom" class="btn btn-default">Save</button>
	  	<% else %>
	  		From:
			<% end %>
			<span class="address"><%=@ride_data[2]["results"][0]["formatted_address"]%></span>
		</div>
		<div id="toAddress">
			<% if @current_user %>
	  		<button id="saveTo" class="btn btn-default">Save</button>
	  	<% else %>
	  		To:
			<%end%>
			<span class="address"><%=@ride_data[1]["results"][0]["formatted_address"]%></span>
		</div>

		<div class="row">
			<div class="col-xs-12 col-sm-7">
				<div class="row">
					<div class="col-xs-5 col-xs-offset-1">
						<div class="well uber">
							<% if @ride_data[0][0] != nil %>
								<li id="<%= @ride_data[0][0].display_name.tr(" ", "") %>"><%= @ride_data[0][0].estimate %></li>
								<% if @ride_data[0][0].surge_multiplier != nil && @ride_data[0][0].surge_multiplier > 1 %>
						    	<%= @ride_data[0][0].surge_multiplier %>x Surge 
						    <%end%>
								<li>UberX</li>
							<% end %>				
						</div>
					</div>
					<div class="col-xs-5">
						<div class="well lyft">
							<% if @ride_data[0][3] != nil %>
								<li id="<%=@ride_data[0][3].display_name.tr(" ", "")%>"><%=@ride_data[0][3].estimate%> </li>
								<li>Lyft</li>
							<%end%>
						</div>
					</div>
				</div>
				<div class="row">		
					<div class="col-xs-5 col-xs-offset-1">
						<div class="well uber">
							<% if @ride_data[0][1] != nil %>
								<li id="<%= @ride_data[0][1].display_name.tr(" ", "") %>"><%= @ride_data[0][1].estimate %></li>
								<% if @ride_data[0][1].surge_multiplier != nil && @ride_data[0][1].surge_multiplier > 1 %>
						    	<%= @ride_data[0][0].surge_multiplier %>x Surge 
						    <%end%>
								<li>Uber Black</li>
							<% end %>
						</div>
					</div>
					<div class="col-xs-5">
						<div class="well lyft">
							<% if @ride_data[0][4] != nil %>
								<li id="<%=@ride_data[0][4].display_name.tr(" ", "")%>"><%=@ride_data[0][4].estimate%> </li>
								<li>Lyft Plus</li>
							<%end%>
						</div>
					</div>			
				</div>
				<div class="row">
					<div class="col-xs-5 col-xs-offset-1">
						<div class="well uber">
							<% if @ride_data[0][2] != nil %>
								<li id="<%= @ride_data[0][1].display_name.tr(" ", "") %>"><%= @ride_data[0][2].estimate %></li>
								<% if @ride_data[0][2].surge_multiplier != nil && @ride_data[0][2].surge_multiplier > 1 %>
						    	<%= @ride_data[0][0].surge_multiplier %>x Surge  
						    <%end%>
								<li>Uber SUV</li>
							<% end %>
						</div>
					</div>
					<div class="col-xs-5">
						<p class="prime-time">Is it Prime Time?</p>
						<button id="minus" class="btn btn-default">-</button>
						<input id="surge" class="input-lg" type="number" min="1" max="20" step=".25" value="1"></input>
						<button id="plus"class="btn btn-default">+</button>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-5 col-xs-offset-1">
						<p class="promo">Uber Promo Code: <%= @codes["ubercode"] %></p>
						<button id="clickable1" class="btn btn-default android apple" hidden><a href="<%=@uberString%>">Request UBER</a></button>
					</div>
					<div class="col-xs-5">
						<p class="promo">Lyft Promo Code: <%= @codes["lyftcode"] %></p>
						<button id="clickable2" class="btn btn-default android apple" hidden><a href="lyft://app">Request LYFT</a></button>
					</div>
				</div>

			</div>
			<div class="col-xs-5 map-holder">
				<div id="map"></div>
			</div>
		</div>

</div>
<script type="text/javascript" src="/fullpage-results.js"></script>

<script>
	var from, to, directionsDisplay, directionsService
	function initMap() {
		setTimeout(function() {
		  from = new google.maps.LatLng(<%=@location["dlat"]%>, <%=@location["dlon"]%>);
		  to = new google.maps.LatLng(<%=@location["slat"]%>, <%=@location["slon"]%>);
		  directionsService = new google.maps.DirectionsService();
		  directionsDisplay = new google.maps.DirectionsRenderer();
		  var mapOptions = {
		    zoom:18,
		    center: from
		  }
		  map = new google.maps.Map(document.getElementById("map"), mapOptions);
		  directionsDisplay.setMap(map);
		  setTimeout(function() {
		  	calcRoute();
		  }, 50);
		}, 50);
	}


	function calcRoute() {
	  var request = {
	    origin:from,
	    destination:to,
	    travelMode: google.maps.TravelMode.DRIVING
	  };

	  directionsService.route(request, function(result, status) {
	    if (status == google.maps.DirectionsStatus.OK) {
	      directionsDisplay.setDirections(result);
	    }
	  });
	}
</script>
<script src="/results.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_OcPqd4-0Dsx7LK_3wHvVzvKcJRWSwjQ&libraries=places&callback=initMap"></script>